services:
  # Web API Service
  - type: web
    name: newsletter-api-v2
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://newsletter_db_v3_user:VHpHOSx5hObdEa6nKTG0iv03i54QIjTm@dpg-d3h9c2juibrs73aome20-a/newsletter_db_v3"
      - key: OPENAI_API_KEY
        sync: false  # You'll set this manually in Render dashboard
      - key: GOOGLE_CSE_API_KEY
        sync: false  # Optional - set if you want CSE features
      - key: GOOGLE_CSE_CX_ID
        sync: false  # Optional - set if you want CSE features

  # Background Worker Service
  - type: worker
    name: newsletter-bg-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python standalone_worker.py"  # Use standalone worker with explicit environment setup
    envVars:
      - key: DATABASE_URL
        value: "postgresql://newsletter_db_v3_user:VHpHOSx5hObdEa6nKTG0iv03i54QIjTm@dpg-d3h9c2juibrs73aome20-a/newsletter_db_v3"
      - key: OPENAI_API_KEY
        sync: false  # You'll set this manually in Render dashboard
      - key: GOOGLE_CSE_API_KEY
        sync: false  # Optional - set if you want CSE features
      - key: GOOGLE_CSE_CX_ID
        sync: false  # Optional - set if you want CSE features
      - key: TIMEZONE
        value: "America/New_York"  # Adjust to your timezone

# Using external database - configuration removed