services:
  - type: web
    name: newsletter-api-v3-clean
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
    healthCheckPath: /health